export default [
    { text: 'JavaScript', value: 100 },
    { text: 'TypeScript', value: 100 },
    { text: 'RxJS', value: 100 },
    { text: 'NGRX', value: 100 },
    { text: 'Redux', value: 100 },
    { text: 'Karma', value: 100 },
    { text: 'Jest', value: 100 },
    { text: 'Jasmine', value: 100 },
    { text: 'Protractor', value: 100 },
    { text: 'Angular', value: 100 },
    { text: 'Angular.js', value: 100 },
    { text: 'React.js', value: 100 },
    { text: 'React Native', value: 100 },
    { text: 'PHP', value: 100 },
    { text: 'Java', value: 100 },
    { text: 'Node.js', value: 100 },
    { text: 'OpenShift', value: 97 },
    { text: 'Jenkins', value: 98 },
    { text: 'Docker', value: 99 },
    { text: 'Github', value: 101 },
    { text: 'VsCode', value: 102 },
    { text: 'IntelliJ', value: 103 },
  ];